---
# # tasks file for image_builder
- name: Setup osbuild server
  ansible.builtin.import_role:
    name: infra.osbuild.setup_server
  vars:
    builder_custom_repos: "{{ microshift_image_custom_repos }}"
    builder_compose_pkgs: "{{ microshift_image_compose_pkgs }}"

- name: enable microshift rpm repos on host
  community.general.rhsm_repository:
    name:
      - rhocp-4.12-for-rhel-8-{{ ansible_architecture }}-rpms 
      - fast-datapath-for-rhel-8-{{ ansible_architecture }}-rpms
    state: enabled

- name: install reposync and createrepo from yum-utils
  ansible.builtin.dnf:
    name:
      - yum-utils
      - createrepo
    state: present

- name: sync microshift packages to the host
  ansible.builtin.command:
    cmd: "/usr/bin/reposync --arch={{ ansible_architecture }} --arch=noarch --gpgcheck --download-path REPO_PATH=/var/repos/microshift-local --repo=rhocp-4.12-for-rhel-8-{{ ansible_architecture }}-rpms --repo=fast-datapath-for-rhel-8-{{ ansible_architecture }}-rpms"

- name: remove coreos packages to avoid conflicts
  ansible.builtin.command:
    cmd: "/usr/bin/find /var/repos/microshift-local -name \\*coreos\\* -exec rm -f {} \\;"

- name: create local rpm repo
  ansible.builtin.command:
    cmd: "/usr/bin/createrepo /var/repos/microshift-local"

- name: Running osbuild image builder
  ansible.builtin.import_role:
    name: infra.osbuild.builder
  vars:
    builder_blueprint_name: "{{ microshift_image_blueprint_name }}"
    builder_blueprint_src_path: "{{ microshift_image_blueprint_src_path }}"
    builder_compose_type: "{{ microshift_image_compose_type }}"
    pubkey_file: "{{ microshift_image_pubkey_file }}"
    builder_compose_customizations: "{{ microshift_image_compose_customizations }}"
