---
# defaults file for image_builder
microshift_rhsm_repos:
    - "rhocp-4.12-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}-rpms"
    - "fast-datapath-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}-rpms"
microshift_image_compose_pkgs:
  - microshift
  - NetworkManager-wifi
  - firewalld
microshift_image_firewall_options:
  # network_access_to_pods (mandatory)
  - zone: trusted
    source: 10.42.0.0/16
  # network_access_to_services (mandatory)
  - zone: trusted
    source: 169.254.169.1
